# Generated by Django 4.2 on 2023-12-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='uploads')),
            ],
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('priority', 'due_date')},
        ),
        migrations.AddField(
            model_name='task',
            name='photos',
            field=models.ManyToManyField(related_name='tasks', to='tasks.photo'),
        ),
    ]
